version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: typescript-express-boilerplate-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - typescript-express-boilerplate-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: typescript-express-boilerplate-pgadmin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - typescript-express-boilerplate-network

volumes:
  postgres_data:

networks:
  typescript-express-boilerplate-network:
    driver: bridge
