version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: typescript-express-boilerplate-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=typescript-express-boilerplate
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - typescript-express-boilerplate-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: typescript-express-boilerplate-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - typescript-express-boilerplate-network

volumes:
  mongodb_data:

networks:
  typescript-express-boilerplate-network:
    driver: bridge
